### ISSUE TITLE
Ação de aceitar/recusar não deve ficar liberada para o new user

### ISSUE THREAD

**Issue by gabicavalcante** [Dayof/PyLadiesBot#5]
O menu para aceitar e recusar está aparecendo também para o novo usuário. Deixar o menu ativo somente para as usuárias já aceitas.

**Comment by Dayof** [comment]
Não sei retirar a visibilidade do menu para a nova usuária, porém deixei ele inativo para ela, qualquer ação que ela tente fazer com os botões a mensagem 'Aguarde aprovação do grupo.' será mostrada à pessoa.
